### ISSUE TITLE
gone_branches doesn't seem to match anything?

### ISSUE THREAD

**Issue by jtzero** [dfedde/git-clean-branches#2]
git version: git version 2.24.3 (Apple Git-128)

I added a set -x
```
if [ "$dry_run" == 'true' ]; then
	gone_branches $remote
	exit
fi
set -x
for branch in $(gone_branches $remote); do
	git branch $delete_flag "$branch"
done
```

ran `git-clean-branches` and it produced this
```
❯ git-clean-branches
no remote given defaulting to origin
++ gone_branches origin
++ local remote=origin
++ git branch -vv
++ sed 's/^\*//'
++ grep 'origin/.*: gone]'
++ awk '{print $1}'
```

this grep won;t match aything
`git branch -vv | sed "s/^\*//"| grep "origin/.*: gone]"`

`grep branch -vv` produces something akin to
```
add_domain            11d8899 [origin/add_domain] adds a domain
adds-logging          7de32d5 [origin/adds-logging] adds logging
```

**Comment by dfedde** [comment]
I think this is working as expected.

This plugin expects that a `git fetch --prune` has been called ( or `fetch.prune` is set to `true`), which removes any remote-tracking references that no longer exist on the remote but does not remove the local branch tacking that remote. When `git fetch --prune` is run and remote-tracking references where removed the output of `git branch -vv` looks something like:
```
  cool_branch_name               2e807d7 [origin/cool_branch_name: gone] Cool commit title
```

A segment about this could be added to the readme or a some help text could be presented when the tool does not find any branches to remove ( we could assume that when someone runs this tool they are expecting branches in a state that would be removed by this tool).

Another option would be to have this tool call `git fetch --prune`. I personally do not like this though as it could mutate references unexpectedly. I think it is better to leave `git` with that control as there are already settings to automate the pruning.

**Comment by jtzero** [comment]
ok I was not aware that prune had to be ran first, I was expecting it to take care of that.
